# Generated by Django 2.2.24 on 2025-02-11 20:12

from django.db import migrations


def get_is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0004_auto_20250211_2227'),
    ]

    operations = [
        migrations.RunPython(get_is_new_building),
    ]
