# Generated by Django 2.2.24 on 2025-02-12 14:16

from django.db import migrations


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_auto_20250212_1705'),
    ]

    operations = [
        migrations.RunPython(transfer_owners),
    ]
