# Generated by Django 2.2.24 on 2025-02-12 15:05

from django.db import migrations


def transfer_flats_info(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.set(Flat.objects.filter(owner=owner.owner))

        # owner.owner_pure_phone = owner.flats.owner_pure_phone
        # owner.owner_phone = owner.flats.owner_phone

        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0014_auto_20250212_1940'),
    ]

    operations = [
        migrations.RunPython(transfer_flats_info),
    ]
