# Generated by Django 2.2.24 on 2025-02-12 16:48

from django.db import migrations


def transfer_flats_info(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flat = owner.flats.first()
        owner.owner_pure_phone = flat.owner_pure_phone
        owner.owners_phonenumber = flat.owners_phonenumber
        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0013_auto_20250212_1805'),
    ]

    operations = [
        migrations.RunPython(transfer_flats_info),
    ]
