# Generated by Django 2.2.24 on 2025-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20250212_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwnerOwnedFlats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'property_owner_owned_flats',
                'managed': False,
            },
        ),
    ]
