# Generated by Django 2.2.24 on 2025-02-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_propertyownerownedflats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyOwnerOwnedFlats',
        ),
    ]
